### ISSUE TITLE
Adding Find in Pages for a specific section like in the search bar if we need to find anything directly any term we can directly get to that word 

### ISSUE THREAD

**Issue by AbdullahKazi500** [chtnnh/qindia-qbi#1]
Adding Find in Pages for a specific section like in the search bar if we need to find anything directly for example quantum when we search for this for example like quantum it directly skips to how many times quantum is mentioned in the blogs

**Comment by chtnnh** [comment]
This functionality can be achieved in any modern browser via `find all`

for example, in Firefox, all you need to do is press Ctrl + F, hence I am closing this issue.
